#pragma once

enum class MessageType{
    LOGIN,
    LOGOUT,
    ADD_USER,
    DELETE_USER,
    INFORM_USER_DELETION,
    CHANGE_PASSWORD,
    GET_USER_LOG,
    GET_CHATROOM_LOG,
    CREATE_CHATROOM,
    INVITE_USER_TO_CHATROOM,
    JOIN_CHATROOM,
    LEAVE_CHATROOM,
    USER_TO_USER_MESSAGE,
    USER_TO_CHATROOM_MESSAGE,
    UPDATE_USER_MAP,
    UPDATE_CHATROOM_MAP,
    UNDEFINED,
    TEST,
    SEND,
    RECV,
    ACK
};
