#!/user/bin/env bash

set -euo pipefail

echo "[Hook] Verifying build & tests before commit..."

BUILD_DIR="build/temp"

cmake -S . -B "$BUILD_DIR" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

cmake --build "$BUILD_DIR" --parallel

cd "$BUILD_DIR"
ctest --output-on-failure

TEST_RESULT=$?
if ["$TEST_RESULT" -ne 0]; then
    echo "[Hook] X Commit aborted: Tests failed!"
    exit 1
fi

echo "[Hook] O All Tests Passed! Committing..."
exit 0

